# Usa Node 20
FROM node:20

# Cria o diretório de trabalho
WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

# Instala pnpm e dependências
RUN npm install -g pnpm \
    && pnpm install

#Copia todo o projeto
COPY . .

EXPOSE 8080

#Roda o servidor TypeScript diretamente via ts-node
CMD ["npx", "ts-node", "src/server.ts"]